"""
Deploy the KidneyDL CT Scan Classifier to Hugging Face Spaces.

Uses the HF Hub Python API, which handles binary files (model.h5) via xet
storage automatically — no git-lfs or git-xet configuration needed.

Usage:
    python deploy_to_hf.py
"""

import os
from dotenv import load_dotenv
from huggingface_hub import HfApi

load_dotenv()  # reads HF_TOKEN from .env file
HF_TOKEN = os.environ.get("HF_TOKEN")
if not HF_TOKEN:
    raise SystemExit("HF_TOKEN not found. Add it to your .env file: HF_TOKEN=hf_...")
REPO_ID = "Sentoz/kidney-classifier"
REPO_TYPE = "space"

# Files and folders to skip when uploading
IGNORE_PATTERNS = [
    # Research notebooks and raw data
    "research/*",
    "*.ipynb",
    ".ipynb_checkpoints/*",
    # Git internals
    ".git/*",
    ".gitignore",
    ".gitattributes",
    # DVC cache (only the cache, not the .dvc pointer files)
    ".dvc/cache/*",
    ".dvc/tmp/*",
    # CT scan training images (large, not needed for serving)
    "artifacts/data_ingestion/*",
    # Upload temp folder
    "uploads/*",
    # Python caches
    "__pycache__/*",
    "*.pyc",
    "*.pyo",
    "*.pyd",
    "*.egg-info/*",
    "dist/*",
    "build/*",
    # Secrets
    ".env",
    # Editor noise
    ".vscode/*",
    ".idea/*",
    "*.DS_Store",
    "Thumbs.db",
    # This script itself
    "deploy_to_hf.py",
    # CI/CD (not needed in the Space)
    ".github/*",
    # Docker compose (HF uses only Dockerfile)
    "docker-compose.yml",
    # Scores (regenerated by the pipeline)
    "scores.json",
    # MLflow local runs
    "mlruns/*",
    "logs/*",
]


def main():
    api = HfApi(token=HF_TOKEN)

    print(f"Uploading to {REPO_ID} ...")
    print("This may take a few minutes (the trained model is ~57 MB).\n")

    api.upload_folder(
        folder_path=".",
        repo_id=REPO_ID,
        repo_type=REPO_TYPE,
        ignore_patterns=IGNORE_PATTERNS,
        commit_message="Deploy KidneyDL CT Scan Classifier",
    )

    print("\nDone! Your Space is building at:")
    print(f"  https://huggingface.co/spaces/{REPO_ID}")


if __name__ == "__main__":
    main()
