name: CD - Deploy to Hugging Face Spaces

on:
  push:
    branches: [main]

jobs:
  deploy:
    name: Push to Hugging Face Spaces
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true

      - name: Push to Hugging Face Spaces
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config user.email "sentongogray1992@gmail.com"
          git config user.name "Paul Sentongo"
          git remote add hf https://sentongo-web:$HF_TOKEN@huggingface.co/spaces/sentongo-web/kidney-classifier
          git push hf main --force
